### ISSUE TITLE
Wrong Chrome logo

### ISSUE THREAD

**Issue by bramus** [web-platform-dx/baseline-status#12]
The Chrome logo shows a green dot at the center. This is not correct, as it should be blue.

A correct SVG can be found over at https://github.com/alrra/browser-logos/blob/main/src/chrome/chrome.svg

**Comment by rachelandrew** [comment]
I've made a PR, but it'll need a maintainer to check and merge it, I just replaced the svg data for the one above, but I'm not set up to test it.
